name: CI-BlackDuck-PR
on:
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Black Duck Scan
        uses: synopsys-sig/synopsys-action@v1.8.0
        
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          
        with:
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          
           ### PULL REQUEST COMMENTS: Uncomment below to enable
          blackduck_prcomment_enabled: true 
          github_token: ${{ secrets.GH_TOKEN }} # Required when PR comments is enabled
